spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/diarypic_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

ai-server:
  base-url: http://localhost:8000