spring:
  profiles:
    active: local # local or docker
  jackson:
    serialization:
      fail-on-empty-beans: false

  # 공통 Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 공통 JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  # 공통 Cloud 설정
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: diarypic-photo
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  # 공통 Security 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}

            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

google:
  maps:
    api:
      key:
# 공통 JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

# 공통 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

# 공통 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# baseUrl 설정
base-url: ${BASE_URL:http://localhost:8080}