spring:
  profiles:
    active: docker
  config:
    import: classpath:application-secret.yml
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret: my-secret-key-which-is-very-secret-and-long-enough123456
  expiration-ms: 3600000

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
