spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diarypic_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ?? ??? update / ?? ?? validate or none ??
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false # ??: false ? ??? ????? ????? fetch

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
